name: "ci"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up magic-nix-cache-action
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: muggle
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check for NixOS configuration changes
        id: nixos-changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'nixos/' && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"

      - name: Check for Home Manager configuration changes
        id: home-changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'home-manager/' && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"

      - name: Build and push NixOS Configuration
        if: steps.nixos-changes.outputs.changed == 'true'
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel
          nix path-info --recursive .#nixosConfigurations.nixos.config.system.build.toplevel | cachix push muggle

      - name: Build and push Home Manager Configuration
        if: steps.home-changes.outputs.changed == 'true'
        run: |
          nix build .#homeConfigurations."muggle@nixos".activationPackage
          nix path-info --recursive .#homeConfigurations."muggle@nixos".activationPackage | cachix push muggle

      - name: Test configurations
        run: |
          nix flake check
