name: "ci"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up magic-nix-cache-action
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: muggle
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check for configuration changes
        id: config-changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '(nixos/|home/)' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Build and push NixOS Configuration (including Home Manager)
        if: steps.config-changes.outputs.changed == 'true'
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel
          nix path-info --recursive .#nixosConfigurations.nixos.config.system.build.toplevel | cachix push muggle

      - name: Test configurations
        run: |
          nix flake check
