name: "ci"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: muggle
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS Configuration
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel

      - name: Push NixOS build to Cachix
        run: |
          nix path-info --recursive .#nixosConfigurations.nixos.config.system.build.toplevel | cachix push muggle

      - name: Build Home Manager Configuration
        run: |
          nix build .#homeConfigurations."muggle@nixos".activationPackage

      - name: Push Home Manager build to Cachix
        run: |
          nix path-info --recursive .#homeConfigurations."muggle@nixos".activationPackage | cachix push muggle

      - name: Test configurations
        run: |
          nix flake check
