#name: "ci"
#
#on:
#  pull_request:
#  push:
#
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: cachix/install-nix-action@v25
#        with:
#          nix_path: nixpkgs=channel:nixos-unstable
#      - uses: cachix/cachix-action@v14
#        with:
#          name: muggle
#          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
#      - run: nix build
#      - run: cachix push muggle
#      - run: nix-shell --run "echo OK"
name: "ci"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: muggle
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS Configuration
        run: |
          nix build .#nixosConfigurations.nixos

      - name: Push to Cachix
        run: cachix push muggle
        env:
          CACHIX_AUTH: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Test Home Manager Configuration
        run: |
          nix build .#homeConfigurations."muggle@nixos"
          cachix push muggle
